from flask import Flask, render_template, request, send_file
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import io

app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/invoice', methods=['POST'])
def invoice():
    seller_name = request.form['seller_name']
    seller_tax = request.form['seller_tax']
    client_name = request.form['client_name']
    service = request.form['service']
    price = float(request.form['price'])
    vat = price * 0.20
    total = price + vat

    # Create PDF in memory
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Title
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(50, height - 60, "EXPRESSDEAL")
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 80, "Invoice")

    # Line
    pdf.line(50, height - 90, width - 50, height - 90)

    # Seller and client
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, height - 120, "From:")
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 140, seller_name)
    pdf.drawString(50, height - 158, f"Tax ID: {seller_tax}")

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, height - 190, "To:")
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 210, client_name)

    # Line
    pdf.line(50, height - 230, width - 50, height - 230)

    # Service and prices
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, height - 260, "Service:")
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 280, service)

    pdf.line(50, height - 300, width - 50, height - 300)

    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 330, f"Price:        {price} MAD")
    pdf.drawString(50, height - 350, f"VAT (20%):    {vat} MAD")
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, height - 380, f"TOTAL:        {total} MAD")

    # Footer
    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, 50, "Generated by ExpressDeal")

    pdf.save()
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"invoice_{client_name}.pdf",
        mimetype='application/pdf'
    )

if __name__ == '__main__':
    app.run(debug=True)
